import { useState } from 'react';
import { createId, Shell, Stat, useLocal, money } from './shared';
import { summarize, csv } from './domain';
type Entry = {
    id: string;
    name: string;
    amount: number;
    category: string;
    kind: 'income' | 'expense';
};
export default function App() { const [items, setItems, error] = useLocal<Entry[]>('ledgerly-v1', [{ id: '1', name: 'Projeto de interface', amount: 4800, category: 'Trabalho', kind: 'income' }, { id: '2', name: 'Assinaturas', amount: 180, category: 'Tecnologia', kind: 'expense' }, { id: '3', name: 'Mercado', amount: 620, category: 'Casa', kind: 'expense' }]); const [filter, setFilter] = useState('Todos'); const stats = summarize(items); const categories = [...new Set(items.map(x => x.category))]; function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const amount = Number(f.get('amount')); const name = String(f.get('name')).trim(); if (!name || !Number.isFinite(amount) || amount <= 0)
    return; setItems([...items, { id: createId(), name, amount, category: String(f.get('category')).trim() || 'Outros', kind: f.get('kind') as Entry['kind'] }]); e.currentTarget.reset(); } function download() { const url = URL.createObjectURL(new Blob(['﻿' + csv(items)], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'ledgerly.csv'; a.click(); URL.revokeObjectURL(url); } return <Shell name="Ledgerly" title="Seu dinheiro, com clareza." description="Entradas, despesas e decisões melhores. Seu painel financeiro pessoal, sem planilhas complicadas." accent="#74e3bf">{error && <p role="alert">Não foi possível salvar no navegador.</p>}<div className="grid"><Stat label="Saldo disponível" value={money(stats.balance)}/><Stat label="Receitas" value={money(stats.income)}/><Stat label="Despesas" value={money(stats.expense)}/></div><section className="panel" style={{ marginTop: 24 }}><h2>Nova movimentação</h2><form className="form" onSubmit={add}><label>Descrição<input name="name" required maxLength={80}/></label><label>Valor (R$)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Categoria<input name="category" required maxLength={40}/></label><label>Tipo<select name="kind"><option value="expense">Despesa</option><option value="income">Receita</option></select></label><button className="primary">Adicionar</button></form></section><section className="panel"><div className="row spread"><h2>Movimentações</h2><div className="row"><label>Filtrar categoria<select value={filter} onChange={e => setFilter(e.target.value)}><option>Todos</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><button onClick={download}>Exportar CSV</button></div></div><div className="scroll"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Valor</th><th>Ação</th></tr></thead><tbody>{items.filter(x => filter === 'Todos' || x.category === filter).map(x => <tr key={x.id}><td>{x.name}</td><td>{x.category}</td><td className={x.kind === 'income' ? 'ok' : 'error'}>{x.kind === 'expense' ? '-' : '+'}{money(x.amount)}</td><td><button aria-label={'Excluir ' + x.name} onClick={() => setItems(items.filter(a => a.id !== x.id))}>Excluir</button></td></tr>)}</tbody></table></div>{!items.length && <p className="empty">Adicione sua primeira movimentação.</p>}</section><section className="panel"><h2>Despesas por categoria</h2>{categories.map(c => { const total = items.filter(x => x.category === c && x.kind === 'expense').reduce((s, x) => s + x.amount, 0); return total > 0 && <div key={c} style={{ marginBottom: 20 }}><div className="row spread"><p>{c}</p><b>{money(total)}</b></div><div className="bar"><span style={{ width: `${stats.expense ? total / stats.expense * 100 : 0}%` }}/></div></div>; })}</section></Shell>; }
